name = "Experimentals Expanded"
uid = "24a0c2f6-59b6-489e-a899-6bba42999999"
version = 1
copyright = "PegasusScourge"
description = "Adds various Supreme Commander 2 inspired experimental units and buildings"
author = "PegasusScourge"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
