----****************************************************************************
--**  File     :  lua/ui/help/unitdescriptions.lua
--**  Author(s):  PegasusScourge
--**
--**
--****************************************************************************

Description['pcb4302'] = "The Boomerang is an adaptation of a traditional Guardian Strategic defense system equiped with a redirection utility similar to that found on the Loyalist, capable of redirecting strategic missiles back to their origin. Requires constant upkeep to maintain the alignment of the redirection system. Returned nukes WILL NOT be shot down by Anti-Nuke silos owned by the launching party."
Description['peb2302'] = "Ballistic unit delivery system developed in secrecy by the UEF. With a lack of a direct-fire land experimental, Percivals have seen a high demand in battles all across space. In an effort to quell complaints the Percy (as it is lovingly called) was quote 'Slower than a red-striped glacier', the Noah Unit Cannon was developed to speed it's deployment to the front line. As an added bonus, it can deploy many other units as well."
Description['psl0202'] = "Following the creation of the legandary Ythotha Assault Bot, most Seraphim commanders were satisfied with their battlefield arsenel. However, upon encountering the sheer number of experimentals the other factions could field comparitevely, the Ilshavoh Mk.II was pressed into service, building upon the amazing T2 chassis and adding a mighty, short range teleport device. The device has a teleportation range about 2.5 times the range of the main cannon, but takes a considerable time and energy cost."
Description['psb1301'] = "The Ythana Teleport Tower was an attempt by the Seraphim to use the MicroTeleporter from the Ilshavoh Mk.II on a much larger scale. With infinite range, the Ythana can dispatch any* unit within it's catch field (range deonted) to far away lands with an abundance of lightning. This lightning, however, has made the structure rather explosive.... Warranty void if used to teleport buildings. *While testing the Seraphim noticed instabilities if some large-mass units or volatiles were transported through: these won't teleport. (Hint: Clicking the teleport button whilst a teleport is in progress will cancel the teleport)"
Description['pab2301'] = "Essentially an upgraded Oblivion turret, the Loyalty Cannon is instead capable of changing the loyalty of a unit (or structure) within it's operation range, reprogramming it and forcing it to work for it. This is primarilly used to sway the tides of battle with in-fighting in the ranks of advancing enemy forces. Due to the unique design of the weapon, it cannot be manually targeted, but instead seeks targets of value to exploit."
